### ISSUE TITLE
License information?

### ISSUE THREAD

**Issue by bamos** [sanketkshah/LODLs#2]
Hi @sanketkshah! When you get a chance, can you please add a license to the code in this repository?

**Comment by sanketkshah** [comment]
Sorry for the delay. I've added the MIT License.

**Comment by bamos** [comment]
Thanks!On Nov 9, 2023, at 9:34 AM, Sanket Shah ***@***.***> wrote:﻿
Sorry for the delay. I've added the MIT License.
